### ISSUE TITLE
Unknown CMake command "o3de_pal_dir"

### ISSUE THREAD

**Issue by hypnosaki** [o3de/o3de-multiplayersample#118]
With a fresh install of the latest O3DE (O3DE Stable 21.11 Release) and with all of the prerequisites installed from here:

https://www.o3de.org/docs/welcome-guide/requirements/#microsoft-windows

I can open the O3DE Editor.

Then:

git clone https://github.com/o3de/o3de-multiplayersample.git
C:\O3DE\21.11.2\scripts\o3de.bat register --this-engine
C:\O3DE\21.11.2\scripts\o3de.bat register -p C:/dev/o3de/o3de-multiplayersample
cmake C:\O3DE\21.11.2 -B C:/dev/o3de/o3de-multiplayersample/build -G "Visual Studio 16" -DLY_3RDPARTY_PATH="c:/dev/o3de/3rdparty" -DLY_PROJECTS="C:/dev/o3de/o3de-multiplayersample"

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30140.0
-- The CXX compiler identification is MSVC 19.29.30140.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using package C:/dev/o3de/3rdparty/packages/zlib-1.2.11-rev5-windows
-- Using package C:/dev/o3de/3rdparty/packages/qt-5.15.2-rev4-windows
-- Using package C:/O3DE/21.11.2/python/runtime/python-3.7.10-rev2-windows
-- Using Python 3.7.10 at C:/O3DE/21.11.2/python/runtime/python-3.7.10-rev2-windows/python/python.exe
-- Python: Getting/Checking packages listed in C:/O3DE/21.11.2/python/requirements.txt
-- Python: Getting/Checking packages listed in C:/O3DE/21.11.2/python/requirements.txt - Already up to date.
-- Python: linking C:/O3DE/21.11.2/Tools/LyTestTools into python site-packages...
-- Python: linking C:/O3DE/21.11.2/Tools/RemoteConsole/ly_remote_console into python site-packages...
-- Python: linking C:/O3DE/21.11.2/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages...
-- Python: linking C:/O3DE/21.11.2/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages... - Failed to install C:/O3DE/21.11.2/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools: ERROR: C:/O3DE/21.11.2/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Python: linking C:/O3DE/21.11.2/scripts/o3de into python site-packages...
CMake Error at C:/dev/o3de/o3de-multiplayersample/Gem/Code/CMakeLists.txt:8 (o3de_pal_dir):
  Unknown CMake command "o3de_pal_dir".

-- Configuring incomplete, errors occurred!
See also "C:/dev/o3de/o3de-multiplayersample/build/CMakeFiles/CMakeOutput.log".

============================================================================
CMakeOutput.log contents:

The system is: Windows - 10.0.19042 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/25/2022 12:57:59 PM.
Project "C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\3.22.2\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\3.22.2\CompilerIdC\CompilerIdC.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdC.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate".
Done Building Project "C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\3.22.2\CompilerIdC\CompilerIdC.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.01

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "C:/dev/o3de/o3de-multiplayersample/build/CMakeFiles/3.22.2/CompilerIdC/CompilerIdC.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/25/2022 12:58:00 PM.
Project "C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\3.22.2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\3.22.2\CompilerIdCXX\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdCXX.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
Done Building Project "C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\3.22.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.92

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "C:/dev/o3de/o3de-multiplayersample/build/CMakeFiles/3.22.2/CompilerIdCXX/CompilerIdCXX.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/dev/o3de/o3de-multiplayersample/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_e2854.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30140 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCCompilerABI.c

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e2854.dir\Debug\\" /Fd"cmTC_e2854.dir\Debug\vc142.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.22\Modules\CMakeCCompilerABI.c"

  cmTC_e2854.vcxproj -> C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\CMakeTmp\Debug\cmTC_e2854.exe

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/dev/o3de/o3de-multiplayersample/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_54159.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30140 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCXXCompilerABI.cpp

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_54159.dir\Debug\\" /Fd"cmTC_54159.dir\Debug\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.22\Modules\CMakeCXXCompilerABI.cpp"

  cmTC_54159.vcxproj -> C:\dev\o3de\o3de-multiplayersample\build\CMakeFiles\CMakeTmp\Debug\cmTC_54159.exe

**Comment by lmbr-pip** [comment]
We moved to o3de_pal_dir in https://github.com/o3de/o3de-multiplayersample/pull/107. 

Project is too old, MPS does not have a 2011 branch at this time due to lack of process setting up tracking branches for downstream projects.

**Comment by AMZN-Olex** [comment]
Specifically, this release: https://github.com/o3de/o3de-multiplayersample/releases/tag/2111.2

**Comment by lmbr-pip** [comment]
Please either update O3DE engine or sync from specific MPS release to match engine version.

**Comment by AMZN-Gene** [comment]
@[hypnosaki](https://github.com/hypnosaki) was the provided work around useful? Closing, but feel free to reopen if this is still a problem.

**Comment by hypnosaki** [comment]
Yes, it now works properly!  Thanks!
