### ISSUE TITLE
Game launcher crashes intermittently right after it connects to the server

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de-multiplayersample#123]
**Describe the bug**
It's noticed that the game launcher crashes intermittently right after it connects to the server. I can get 3/5 repros for this issue.

**Steps to reproduce**
1. Build MultiplayerSample.GameLauncher, MultiplayerSample.ServerLauncher and Asset Processor
2. Start MultiplayerSample.ServerLauncher following https://github.com/o3de/o3de-multiplayersample/blob/development/README.md
3. Wait until the server launcher is loaded successfully and start MultiplayerSample.GameLauncher following https://github.com/o3de/o3de-multiplayersample/blob/development/README.md
4. Wait a few seconds for the game launcher to freeze and crash
5. Repeat step 2-4 for a few times since the crash occurs intermittently

**Expected behavior**
The game launcher can connect to the server and run without issues.

**Actual behavior**
The game launcher can sometimes crash right after connect to the server.

**Screenshots/Video**
Call stack:
![image](https://user-images.githubusercontent.com/68558268/157554102-13deb750-7901-492e-80a9-302140b871cf.png)

**Found in Branch**
 MultiplayerSample dev branch at 9918589f and O3DE dev branch at d55d61459

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
Client and server logs:
[Server.log](https://github.com/o3de/o3de-multiplayersample/files/8218813/Server.log)
[Game.log](https://github.com/o3de/o3de-multiplayersample/files/8218814/Game.log)

**Comment by AMZN-Gene** [comment]
I'll try to repro this in another project and I'll move this issue to O3DE if possible.

**Comment by AMZN-Gene** [comment]
Does not repro in AutomatedTesting. No crashing after 5 attempts. Leaving issue in MultiplayerSample repo.

**Comment by allisaurus** [comment]
observation: when I run MPS with a constrained view port (`r_viewportSize 1024 600` for both server and client), this doesn't seem to happen as frequently. Could there be some processing delay or resource constraint contributing to this?

**Comment by AMZN-Olex** [comment]
This has been fixed in stabilization 2205 branch and will make it back to development branch any day now.
See https://github.com/o3de/o3de/pull/9231
