### ISSUE TITLE
Failed to build MultiplayerSample for iOS

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de-multiplayersample#130]
**Describe the bug**
Building MultiplayerSample via command line/xcode can fail at the packaging process with missing assets. 

**Steps to reproduce**
1. Build MultiplayerSample for Android from command line or XCode
2. See error

**Expected behavior**
MultiplayerSample can be built and deployed to iOS devices successfully

**Actual behavior**
Build/packaging failed with the following issues:
![image](https://user-images.githubusercontent.com/68558268/158668322-7e9cc389-f377-48b5-860f-c504ee0ca636.png)

**Found in Branch**
Development@172e344

**Desktop/Device (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Version 14.2

**Comment by lmbr-pip** [comment]
@junbo75 Can we add your workaround here?  It sounds like PNGs are required, can we add to the project?

**Comment by lmbr-pip** [comment]
Can we discuss fix with SIG-platform?

**Comment by junbo75** [comment]
The workaround for this issue is to:
1. Copy [AutomatedTestingAppIcon.appiconset](https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/Resources/IOSLauncher/Images.xcassets/AutomatedTestingAppIcon.appiconset) from AutomatedTesting project to MultiplayerSample project and rename it to MultiplayerSample AppIcon.appiconset
2. Copy https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/Resources/IOSLauncher/Images.xcassets/LaunchImage.launchimage/Contents.json) from AutomatedTesting project to https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Resources/IOSLauncher/Images.xcassets/LaunchImage.launchimage/Contents.json in MultiplayerSample project
3. Copy https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/Resources/IOSLauncher/Images.xcassets/AutomatedTestingAppIcon.appiconset/Contents.json) from AutomatedTesting project to https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Resources/IOSLauncher/Images.xcassets/CMakeTestbedAppIcon.appiconset/Contents.json in MultiplayerSample project
4. Delete https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Resources/IOSLauncher/Images.xcassets/Contents.json

**Comment by junbo75** [comment]
Close this issue for now since the fix has been merged.
