### ISSUE TITLE
MultiplayerSample SampleBase level is not loading properly when launched via ServerLauncher, and GameLauncher executables

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de-multiplayersample#146]
**Describe the bug**
MultiplayerSample SampleBase level is not loading entities containing network components when launched on the MultiplayerSample.ServerLauncher/MultiplayerSample.GameLauncher as a standalone level, or via the host/connect setup. It should be noted that when the Game Mode is started in Editor on the SampleBase level, it works as expected. 

Please refer to the attached Game.log and Server.log files attached in the **Video, Server.log, and Game.log** section.

**Prerequisites**
1. Clone the MultiplayerSample project to a chosen folder as described on the https://github.com/o3de/o3de-multiplayersample page.
2. In the Project Manager go to New Project... > Add Existing Project, in the Select Project Directory explorer window find and select the cloned o3de-multiplayersample project folder from step 1.
3. Build the MultiplayerSample project in the Project Manager.
4. Launch the MultiplayerSample project, and wait until all assets are processed in the Asset Processor.
5. In the Welcome to O3DE window click Open... and find the SampleBase Level, open it.
6. In the Command Line navigate to the o3de-multiplayersample and build the MultiplayerSample.ServerLauncher executable if not present (Command used during this issue reproduction was: `cmake --build build\windows --target MultiplayerSample.ServerLauncher --config profile`).
7. Go back to the Editor, verify that the level is loaded properly, and the Game Mode is fully functional.

**Steps to reproduce**
1. Make sure all O3DE-related applications are shutdown (e.g. Asset Processor, Editor).
2. Launch the MultiplayerSample.ServerLauncher executable built in the **Prerequisites**.
3. After the ServerLauncher is loaded, press the tilde key (~), and in the Console execute command `loadlevel SampleBase`.
4. Without closing the Console execute another command `host`.
5. Without closing the ServerLauncher window launch the MultiplayerSample.GameLauncher executable.
6. After the GameLauncher is loaded, press the tilde key (~), and in the Console execute command `connect`.
7. Navigate between both the ServerLauncher, and GameLauncher windows, and attempt some input in the scene itself.

**Expected behavior**
The entities containing network components (boxes and player) are spawned.

**Actual behavior**
No network entities are spawned on neither the ServerLauncher nor the GameLauncher.

**Video, Server.log, and Game.log**

https://user-images.githubusercontent.com/86952082/167605193-fb807a29-8731-4e3b-a5b6-9241a1608272.mp4

[Server.log](https://github.com/o3de/o3de/files/8660734/Server.log)
[Game.log](https://github.com/o3de/o3de/files/8660735/Game.log)

**Found in Branch**
Stabilization_2205 (a073665)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lmbr-pip** [comment]
From server log

`
(System) - New incoming connection from remote address: 127.0.0.1:55428
[Warning] (System) - No active NetworkPlayerSpawnerComponents were found on player spawn request.
[Error] (AssetDatabase) - GetAsset called with invalid asset Id.
[Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded.  Asset may be missing, not processed or moved.  AssetId: {00000000-0000-0000-0000-000000000000}:0
[Warning] (System) - Attempt to spawn prefab  failed. Check that prefab is network enabled.
`

**Comment by lmbr-pip** [comment]
Interested if this is a timing issue based on when config files are run vs manual command entering

**Comment by lmbr-pip** [comment]
@robhaco volunteered to run triage/reproduction on issue

**Comment by robhaco** [comment]
Was unable to repro this with the latest stabilization installer with the latest version of MultiplayerSample project, but I'd like to give it another shot with the new release and possibly development, just to be sure.

**Comment by lmbr-pip** [comment]
No longer an issue, main level has also changed to NewStarBase. Closing as stale/DNR

**Comment by LB-KacperBieniek** [comment]
Confirming the issue has been closed. SampleBase level is no longer a part of MultiplayerSample project.
