### ISSUE TITLE
SpawningPerfTest Level Is Missing NetworkPlayerSpawner 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#151]
**Describe the bug**
The performance test level isn't working because it's missing a player spawner.

**Steps to reproduce**
1. Open Editor
2. Open SpawningPerfTest level
3. CTRL+G

**Expected behavior**
We see the player spawn in and the world starts spawning gold boxes (golden spawnables)

**Actual behavior**
The player never spawns in because the level isn't set up to use the new player spawner system.

**Comment by lmbr-pip** [comment]
This is now fixed.
