### ISSUE TITLE
Server crashes shortly after client connect due to EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de-multiplayersample#152]
**Describe the bug**
When running MPS, server will frequently (4/5 tests) error out shortly after client connection with the following:
```
// from user/log/error.log

Executable: MultiplayerSample.ServerLauncher.exe (debug: no
Exception Code: 0xC0000005
Exception Addr: 0x0033:0x00007FF88DE01253
Exception Module: 
Exception Description: EXCEPTION_ACCESS_VIOLATION, Attempt to read from address 0x00000191
The memory could not be "read"
Call Stack Trace:
22) 00007FF9507CFF27 (KERNELBASE) : UnhandledExceptionFilter
21) 00007FF952EF51B0 (ntdll) : memset
20) 00007FF952EDC766 (ntdll) : _C_specific_handler
19) 00007FF952EF209F (ntdll) : _chkstk
18) 00007FF952EA1454 (ntdll) : RtlRaiseException
17) 00007FF952EF0BCE (ntdll) : KiUserExceptionDispatcher
16) C:\Users\USERNAME\source\o3de\Gems\Multiplayer\Code\Source\Components\NetBindComponent.cpp (470) : Multiplayer::NetBindComponent::SerializeStateDeltaMessage
...
```

**Steps to reproduce**
1. Build MPS server and game launchers per [README](https://github.com/o3de/o3de-multiplayersample/blob/development/README.md#step-3-configure-and-build)
2. Run server launcher: `MultiplayerSample.ServerLauncher.exe --console-command-file=server.cfg`
3. Wait until a few seconds after server is running, then run game launcher: `MultiplayerSample.GameLauncher.exe --console-command-file=client.cfg`
4. navigate player around client map for 3-15 seconds, until server stops responding and exits.

**Expected behavior**
Server remains alive and responsive well after client connect.

**Actual behavior**
Server stops responding and crashes with error.

**Assets required**
N/A

**Screenshots/Video**
Shortly before the server crashes, the client can be seen struggling to load entities (see missing blocks)
![image](https://user-images.githubusercontent.com/34254888/171735137-b5cb6371-04c2-4853-947a-0833f58d679f.png)

**Found in Branch**
development:
* O3DE: `b6fb43f091`
* o3de-multiplayersample: `a95beb2a5`

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows 10 Enterprise
 - CPU: Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz   3.10 GHz
 - GPU: NVIDIA GeForce RTX 3070
 - Memory: 32GB

**Additional context**
[error.log](https://github.com/o3de/o3de-multiplayersample/files/8827763/error.log)
[Server.log](https://github.com/o3de/o3de-multiplayersample/files/8827764/Server.log)
[Game.log](https://github.com/o3de/o3de-multiplayersample/files/8827766/Game.log)

**Comment by lmbr-pip** [comment]
I could not reproduce this, asking Rob to retest

**Comment by robhaco** [comment]
@lmbr-pip I was able to reproduce this in latest development.  There also appears to be a bit more information in the server.log which seems is likely related.
`<15:37:29> [Error] (EMotionFX) - Cannot create snapshot as anim graph instance has not been created yet. Please make sure you selected an anim graph in the anim graph component.
<15:37:29> (System) - 
==================================================================
<15:37:29> (System) - Trace::Assert
 C:/o3de/Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp(738): (15660) 'unsigned __int64 __cdecl EMotionFX::Integration::ActorComponent::GetJointIndexByName(const char *) const'
<15:37:29> (System) - The actor instance needs to be valid.
<15:37:29> (System) - ------------------------------------------------
<15:37:44> (System) - C:\o3de\Gems\EMotionFX\Code\Source\Integration\Components\ActorComponent.cpp (740) : EMotionFX::Integration::ActorComponent::GetJointIndexByName
<15:37:44> (System) - C:\Users\USERNAME\.o3de\Projects\mps\Gem\Code\Source\Components\NetworkWeaponsComponent.cpp (369) : MultiplayerSample::NetworkWeaponsComponentController::ProcessInput
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\Components\NetBindComponent.cpp (343) : Multiplayer::NetBindComponent::ProcessInput
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\Components\LocalPredictionPlayerInputComponent.cpp (215) : Multiplayer::LocalPredictionPlayerInputComponentController::HandleSendClientInput
<15:37:44> (System) - C:\Users\USERNAME\.o3de\Projects\mps\build\windows\External\Multiplayer-184c99d3\Code\Azcg\Generated\Source\AutoGen\LocalPredictionPlayerInputComponent.AutoComponent.cpp (520) : Multiplayer::LocalPredictionPlayerInputComponentBase::HandleRpcMessage
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\Components\NetBindComponent.cpp (360) : Multiplayer::NetBindComponent::HandleRpcMessage
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\NetworkEntity\EntityReplication\EntityReplicator.cpp (724) : Multiplayer::EntityReplicator::HandleRpcMessage
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\NetworkEntity\EntityReplication\EntityReplicationManager.cpp (879) : Multiplayer::EntityReplicationManager::HandleEntityRpcMessages
<15:37:44> (System) - C:\Users\USERNAME\.o3de\Projects\mps\build\windows\External\Multiplayer-184c99d3\Code\Azcg\Generated\Source\AutoGen\Multiplayer.AutoPacketDispatcher.inl (132) : MultiplayerPackets::DispatchPacket<Multiplayer::MultiplayerSystemComponent>
<15:37:44> (System) - C:\o3de\Code\Framework\AzNetworking\AzNetworking\UdpTransport\UdpNetworkInterface.cpp (300) : AzNetworking::UdpNetworkInterface::Update
<15:37:44> (System) - C:\o3de\Code\Framework\AzNetworking\AzNetworking\Framework\NetworkingSystemComponent.cpp (79) : AzNetworking::NetworkingSystemComponent::OnSystemTick
<15:37:44> (System) - C:\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents> >::Broadcast<void (__cdecl AZ::SystemTic
<15:37:44> (System) - C:\o3de\Code\Framework\AzCore\AzCore\Component\ComponentApplication.cpp (1357) : AZ::ComponentApplication::TickSystem
<15:37:44> (System) - C:\o3de\Code\LauncherUnified\Launcher.cpp (564) : O3DELauncher::Run
<15:37:44> (System) - C:\o3de\Code\LauncherUnified\Platform\Windows\Launcher_Windows.cpp (35) : WinMain
<15:37:44> (System) - d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
<15:37:44> (System) - 00007FF8B4077034 (KERNEL32) : BaseThreadInitThunk
<15:37:44> (System) - 00007FF8B5222651 (ntdll) : RtlUserThreadStart
<15:37:44> (System) - ==================================================================
<15:37:44> (System) - ====Assert added to ignore list by spec and verbosity setting.====
<15:37:44> (System) - 
==================================================================
<15:37:44> (System) - Trace::Assert
 C:\o3de\Gems\EMotionFX\Code\Source\Integration/System/SystemCommon.h(133): (15660) 'class EMotionFX::ActorInstance *__cdecl EMotionFX::Integration::EMotionFXPtr<class EMotionFX::ActorInstance>::operator ->(void) const'
<15:37:44> (System) - Attempting to dereference a null EMotion FX object pointer.
<15:37:44> (System) - ------------------------------------------------
<15:37:44> (System) - C:\o3de\Gems\EMotionFX\Code\Source\Integration\Components\ActorComponent.cpp (740) : EMotionFX::Integration::ActorComponent::GetJointIndexByName
<15:37:44> (System) - C:\Users\USERNAME\.o3de\Projects\mps\Gem\Code\Source\Components\NetworkWeaponsComponent.cpp (369) : MultiplayerSample::NetworkWeaponsComponentController::ProcessInput
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\Components\NetBindComponent.cpp (343) : Multiplayer::NetBindComponent::ProcessInput
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\Components\LocalPredictionPlayerInputComponent.cpp (215) : Multiplayer::LocalPredictionPlayerInputComponentController::HandleSendClientInput
<15:37:44> (System) - C:\Users\USERNAME\.o3de\Projects\mps\build\windows\External\Multiplayer-184c99d3\Code\Azcg\Generated\Source\AutoGen\LocalPredictionPlayerInputComponent.AutoComponent.cpp (520) : Multiplayer::LocalPredictionPlayerInputComponentBase::HandleRpcMessage
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\Components\NetBindComponent.cpp (360) : Multiplayer::NetBindComponent::HandleRpcMessage
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\NetworkEntity\EntityReplication\EntityReplicator.cpp (724) : Multiplayer::EntityReplicator::HandleRpcMessage
<15:37:44> (System) - C:\o3de\Gems\Multiplayer\Code\Source\NetworkEntity\EntityReplication\EntityReplicationManager.cpp (879) : Multiplayer::EntityReplicationManager::HandleEntityRpcMessages
<15:37:44> (System) - C:\Users\USERNAME\.o3de\Projects\mps\build\windows\External\Multiplayer-184c99d3\Code\Azcg\Generated\Source\AutoGen\Multiplayer.AutoPacketDispatcher.inl (132) : MultiplayerPackets::DispatchPacket<Multiplayer::MultiplayerSystemComponent>
<15:37:44> (System) - C:\o3de\Code\Framework\AzNetworking\AzNetworking\UdpTransport\UdpNetworkInterface.cpp (300) : AzNetworking::UdpNetworkInterface::Update
<15:37:44> (System) - C:\o3de\Code\Framework\AzNetworking\AzNetworking\Framework\NetworkingSystemComponent.cpp (79) : AzNetworking::NetworkingSystemComponent::OnSystemTick
<15:37:44> (System) - C:\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents> >::Broadcast<void (__cdecl AZ::SystemTic
<15:37:44> (System) - C:\o3de\Code\Framework\AzCore\AzCore\Component\ComponentApplication.cpp (1357) : AZ::ComponentApplication::TickSystem
<15:37:44> (System) - C:\o3de\Code\LauncherUnified\Launcher.cpp (564) : O3DELauncher::Run
<15:37:44> (System) - C:\o3de\Code\LauncherUnified\Platform\Windows\Launcher_Windows.cpp (35) : WinMain
<15:37:44> (System) - d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
<15:37:44> (System) - 00007FF8B4077034 (KERNEL32) : BaseThreadInitThunk
<15:37:44> (System) - 00007FF8B5222651 (ntdll) : RtlUserThreadStart
<15:37:44> (System) - ==================================================================
<15:37:44> (System) - ====Assert added to ignore list by spec and verbosity setting.====
<15:37:44> (Exit) - Exception with exit code: 0xc0000005
<15:37:44> (Exit) - C:\o3de\Code\Legacy\CrySystem\DebugCallStack.cpp (223) : DebugCallStack::handleException
<15:37:44> (Exit) - 00007FF8B2A8FF27 (KERNELBASE) : UnhandledExceptionFilter
<15:37:44> (Exit) - 00007FF8B52751B0 (ntdll) : memset
<15:37:44> (Exit) - 00007FF8B525C766 (ntdll) : _C_specific_handler
<15:37:44> (Exit) - 00007FF8B527209F (ntdll) : _chkstk
<15:37:44> (Exit) - 00007FF8B5221454 (ntdll) : RtlRaiseException
<15:37:44> (Exit) - 00007FF8B5270BCE (ntdll) : KiUserExceptionDispatcher
<15:37:44> (Exit) - C:\o3de\Gems\EMotionFX\Code\EMotionFX\Source\ActorInstance.cpp (1442) : EMotionFX::ActorInstance::GetActor
<15:37:44> () - 00007FF8B2A8FF27 (KERNELBASE) : UnhandledExceptionFilter
<15:37:44> () - 00007FF8B52751B0 (ntdll) : memset
<15:37:44> () - 00007FF8B525C766 (ntdll) : _C_specific_handler
<15:37:44> () - 00007FF8B527209F (ntdll) : _chkstk
<15:37:44> () - 00007FF8B5221454 (ntdll) : RtlRaiseException
<15:37:44> () - 00007FF8B5270BCE (ntdll) : KiUserExceptionDispatcher
<15:37:44> () - C:\o3de\Gems\EMotionFX\Code\EMotionFX\Source\ActorInstance.cpp (1442) : EMotionFX::ActorInstance::GetActor
`

**Comment by robhaco** [comment]
@lmbr-pip Update upon further testing.  I had noticed that I had some issues with my asset cache while testing another issue.  Upon clearing the cache and reprocessing assets, I'm no longer able to repro this issue.  Since my exception seems to reference the actor asset, I'm thinking the issue may have been related to a stale asset somehow.  Suggest @allisaurus try reproing the issue with clean assets to see if it's the same.

**Comment by allisaurus** [comment]
Thanks, @robhaco ! I tested again w/ latest and clean assets and can no longer reproduce this either. I'm good to close this since a few folks now have not had a problem after reprocessing assets.

**Comment by kberg-amzn** [comment]
> ![image](https://user-images.githubusercontent.com/87345238/177396905-3fd2dc85-0c88-4172-b8d0-b85e7c6e8373.png) From the error log, we're clearly dereferencing data offset from `nullptr` though?

Indeed, it definitely looks like a nullptr dereference. We should make sure we put defensive programming in place to more gracefully detect and handle these situations, we shouldn't be crashing on bad data. Also asset cooking issues are quite an ominous issue indeed. In this case, looking at the code, I suspect one of the components in the net-bound component list was actually nullptr.

```        for (auto iter = m_multiplayerSerializationComponentVector.begin(); iter != m_multiplayerSerializationComponentVector.end(); ++iter)
        {
            success &= (*iter)->SerializeStateDeltaMessage(replicationRecord, serializer);
            stats.RecordComponentSerializeEnd(serializer.GetSerializerMode(), (*iter)->GetNetComponentId());
        }
```

**Comment by jeremyong-az** [comment]
I suppose the easiest thing to do is identify which member variable exists at offset `0x0191` from the base pointer (something easy to check with the VS struct layout extension)
