### ISSUE TITLE
Unable to build o3de-multiplayersample project

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de-multiplayersample#155]
**Describe the bug**
The multiplayersample project fails to build after following the instructions from the readme.md file. During the process multiple errors regarding the PhysX materials are displayed. Launching the Editor afterwards results in several serialization errors being displayed in the Console.
Please refer to the attached files for more details.

**Reproducibility: 1/2**

**Steps to reproduce:**
1. Download the o3de-multiplayersample project.
2. Follow the instructions from the readme.md file (https://github.com/o3de/o3de-multiplayersample).

**Expected behavior**
The o3de-multiplayersample builds without any issues.

**Actual behavior**
The errors are displayed and the Editor does not work correctly.

**Screenshots/Video:**

![CMDErrors](https://user-images.githubusercontent.com/86952591/174306164-995eac84-5871-4c63-8eb4-23e0140690f1.JPG)

**Found in Branch**
Development (8d15edf)
branch o3de-multiplayersample

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Additional context**
[AP_GUI.log](https://github.com/o3de/o3de-multiplayersample/files/8927601/AP_GUI.log)
[Editor.log](https://github.com/o3de/o3de-multiplayersample/files/8927602/Editor.log)
[CMDErrors.txt](https://github.com/o3de/o3de-multiplayersample/files/8927605/CMDErrors.txt)

**Comment by lmbr-pip** [comment]
@LB-JakubSkoczylas - Can you expand on "Download the o3de-multiplayersample project." - you cannot download the zip from Github as we use LFS, you must clone. Can you confirm how you "downloaded" the project?

**Comment by LB-JakubSkoczylas** [comment]
@lmbr-pip I followed the instructions from the readme.md file and I cloned the project.

**Comment by robhaco** [comment]
@LB-JakubSkoczylas can you try to reproduce this issue again with updated engine, etc?  There was an update to the physics materials a bit back which resolved it for me, but it may have been a mismatch you were seeing between engine and MPS.  May also be worth cleaning up your asset cache before retesting.

**Comment by lmbr-pip** [comment]
Closing as no longer reproducible

**Comment by LB-JakubSkoczylas** [comment]
This issue does not occur on build Development (966848d).
