### ISSUE TITLE
Feature Request: Update the README.md with building the project via the Project Manager

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de-multiplayersample#164]
**Is your feature request related to a problem? Please describe.**
Currently the instructions on the https://github.com/o3de/o3de-multiplayersample/blob/development/README.md revolve around building via the Command Line. It is easier to perform project build (especially for newer O3DE users) via the Project Manager.

**Describe the solution you'd like**
Update the README.md instruction with steps that use Project Manager, for example:
If you have the engine already built:
1. Clone the MultiplayerSample project to your project folder (for example `C:\Users\<User>\O3DE\Projects\`) - `git clone https://github.com/o3de/o3de-multiplayersample.git`.
2. Open the Project Manager.
3. In the Project Manager navigate to New Project... > Open Existing Project, and select the cloned MultiplayerSample project.
4. Under the added MultiplayerSample project's tile click the hamburger button, and select Build from the dropdown menu.
5. After the MultiplayerSample finishes building, launch it by clicking "Open Editor" on the project's tile.

**Comment by lmbr-pip** [comment]
Updated in https://github.com/o3de/o3de-multiplayersample#readme

**Comment by LB-ArturZieba** [comment]
Confirming that the feature request has been implemented. There is a section on Project Manager usage in the README.md file now.
