### ISSUE TITLE
MultiplayerSample GameLauncher and ServerLauncher have deprecated O3DE icons

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de-multiplayersample#165]
**Describe the bug**
Icons of the MultiplayerSample.GameLauncher, and MultiplayerSample.ServerLauncher executables built in the cloned MultiplayerSample projects are deprecated (white font on blue background, instead of blue font on white background).

**Steps to reproduce**
1. Clone the MultiplayerSample project to your project folder (for example `C:\Users\<User>\O3DE\Projects\`) - `git clone https://github.com/o3de/o3de-multiplayersample.git`.
2. Open the Project Manager.
3. In the Project Manager navigate to New Project... > Open Existing Project, and select the cloned MultiplayerSample project.
4. Under the added MultiplayerSample project's tile click the hamburger button, and select Build from the dropdown menu.
5. After the MultiplayerSample finishes building, navigate to the project's build folder (for example `C:\Users\<User>\O3DE\Projects\o3de-multiplayersample\build\windows\bin\profile\`), and view the MultiplayerSample.GameLauncher, and MultiplayerSample.ServerLauncher executables.

**Expected behavior**
Launcher executables have the current icons.

**Actual behavior**
Launcher executables have deprecated icons.

**Screenshot**
![MultiplayerSampleLauncherIcons](https://user-images.githubusercontent.com/86952082/176875527-0b3c013b-bec7-4e7b-9a5c-220332fe34f6.PNG)

**Found in Branch**
Development (2a7d81f)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lmbr-pip** [comment]
Fixed in by https://github.com/o3de/o3de-multiplayersample/pull/331

![new_icons_mps](https://user-images.githubusercontent.com/61438964/231015619-557bdded-98c2-4b8f-b235-273c4847acc9.PNG)

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2305 (1ff603a) build.
