### ISSUE TITLE
[FEATURE REQUEST] Full README.md

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de-multiplayersample#174]
Would like to have a full `README.md` and possibly attached documentation for the Multiplayer Sample project (MSP), which users can download and play around with.

Some questions to address may be

    What's a quick explanation of the intent of this project and its core features
    What are the simplest steps to install and set up the provided sample project. (Should user start with a blank project, or download the MSP? Any Gems to build with?)
    What are the most important questions new users will have?
    What are cool things users can do with this project?

Requests to include in this doc

    Add as a prerequisite what the most stable version of O3DE to use with this project.
    Usage of CVARs and .cfg files. Can reference the CVAR docs in "Related topics".

**Describe the solution you'd like**

Update `README.md` with the latest instructions to build and run.

**Describe alternatives you've considered**

Documentation on the website; sig-docs-community does not believe that documentation for sample projects maintained by individual sigs without the approval of an asset/demo/tutorial/sample/etc. SIG or project working group should be maintained within the project itself.

**Additional context**
 Copied from https://github.com/o3de/o3de.org/issues/1632

**Comment by lmbr-pip** [comment]
Believe this is covered in updated https://github.com/o3de/o3de-multiplayersample#readme
