### ISSUE TITLE
Multiple Build Errors cause build Failure

### ISSUE THREAD

**Issue by NovaLogicDev** [o3de/o3de-multiplayersample#177]
**Describe the bug**
CMake Build Fails with Multiple errors.

**Steps to reproduce**
1. clone the repo
2. do step 2 as outlined in the README
3. do step 3 option 1

**Expected behavior**
Successful build

**Actual behavior**
build errors

**Desktop/Device:**
 - OS: Windows 10 Home, 21H2, Build: 19044.1889

**Additional context**
Attached are Log outputs from both CMake commands, and the results of treeing the cloned repository
[out.txt](https://github.com/o3de/o3de-multiplayersample/files/9356231/out.txt)
[tree.txt](https://github.com/o3de/o3de-multiplayersample/files/9356235/tree.txt)

**Comment by lmbr-pip** [comment]
@NovaLogicDev Can you confirm you are on the development branch for both O3DE and o3de-multiplayersample?

**Comment by NovaLogicDev** [comment]
I'm not on O3de development, is that a requirement? where is that documented in the readme?

**Comment by NovaLogicDev** [comment]
Based on that, hint changed branch to main, and the build is now succeeding, might be worth adding a note in the readme cause that's a bit confusing and not obvious, especially because experimental is the default branch.

**Comment by NovaLogicDev** [comment]
Further issues were encountered when attempting to open the project with the editor
![image](https://user-images.githubusercontent.com/39929570/185523440-4dd675f7-542b-4ac3-b5a6-889436ca04f0.png)

**Comment by AMZN-Gene** [comment]
> Based on that, hint changed branch to main, and the build is now succeeding, might be worth adding a note in the readme cause that's a bit confusing and not obvious, especially because experimental is the default branch.

That is confusing. Basically whatever branch you're using from _https://github.com/o3de/o3de_, you want to copy for _https://github.com/o3de/o3de-multiplayersample_. For example, if you're using o3de's development branch, you'd also want to use Multiplayer Samples's development branch.  If you get a chance, it would be great if you could create a github issue in MultiplayerSample and request the docs update :)

**Comment by allisaurus** [comment]
Hey @NovaLogicDev , thanks for providing a screenshot. That error seems to indicate the asset processor can't find the engine assets (see [similar issue](https://github.com/o3de/o3de/issues/3955) which was [patched](https://github.com/o3de/o3de/pull/6234) in 21.11.2).

Could you try re-registering and configuring the project (steps 2 & 3 in the [README](https://github.com/o3de/o3de-multiplayersample/blob/main/README.md)), ensuring that the `c:/path/to/o3de/scripts/o3de` path you enter matches the location of the engine you're trying to use (22.05.0 by the looks of your out.txt file)? You can also check where the asset processor is running from by opening it up from your system tray and checking the root value in the top left:

![image](https://user-images.githubusercontent.com/34254888/186982170-eeab986c-f9f2-4d7d-80cd-e447d6ebb757.png)

If that doesn't help narrow down the problem, then it would also help us to know:

1. Which version of the engine you're using (either confirm its 22.05.0 or let us know if that's not the case)
2. whether you're using the project manager or building the "Editor" Visual Studio target to open the the o3de-multiplayersample project editor
3. whether you have multiple versions of the engine on your machine, such as multiple "official" releases and/or the engine source repo.

**Comment by lmbr-pip** [comment]
No response from OP, closing as stale. Please reopen if you have more information.
