### ISSUE TITLE
As a new User I'd Like Network Stress Test to Be in A Different Level 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#179]
**Is your feature request related to a problem? Please describe.**
BaseSample level contains a network stress test. New users opening the base sample aren't quite sure why it's in the sample level.

**Describe the solution you'd like**
Create a level just for stress testing called "StressTest"

**Comment by lmbr-pip** [comment]
BaseSample has been removed, no longer relevant.
