### ISSUE TITLE
Player Spawner Snap to Ground Doesn't Work

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#180]
**Describe the bug**
Even with snap-to-ground enabled, the Player will spawn in the air.

**Steps to reproduce**
1. Open a new default level
2. Add a player spawner entity and component so it's off the ground
3. Assign a .network.spawnable to the player spawner component
4. CTRL+G to run the level
5. Notice where the player is spawned

**Expected behavior**
The player should spawn on the floor

**Actual behavior**
Player is in the air

**Found in Branch**
August 21, o3de development

**Comment by lmbr-pip** [comment]
No longer relevant. Component has been replaced and we fixed most of the snap to ground issues.
