### ISSUE TITLE
As a New User I'd like the Player to have Gravity Enabled

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#182]
**Is your feature request related to a problem? Please describe.**
It was confusing to create a new level with the player and see him floating in the air. I wasn't sure if I had setup incorrectly.
My set up wasn't incorrect, it was just that MPS doesn't have gravity enabled.

**Describe the solution you'd like**
Enable gravity

**Comment by lmbr-pip** [comment]
Gravity has been added to latest iteration of MPS sample. Resolving.
