### ISSUE TITLE
Update MPS Getting Started CMake Config to Match Project Manager

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#183]
**Is your feature request related to a problem? Please describe.**
The getting start docs says to generate a project inside of a windows_2019 folder, but project manager puts it in a windows folder. 
Then when I built using Project Manager, I had 2 builds unintentionally. 

# example build command
> cmake --build c:/path/to/o3de-multiplayersample/build/windows_vs2019 --target Editor MultiplayerSample.GameLauncher MultiplayerSample.ServerLauncher --config profile -- /m /nologo

**Describe the solution you'd like**
Update the doc so that the build instructions match what Project Manager would do.

**Describe alternatives you've considered**
Update the doc to just use Project Manager instead

**Comment by lmbr-pip** [comment]
We no longer reference vs2019, have fixed all the commands to match latest o3de.org guidance.
