### ISSUE TITLE
WF6: Player Appears All White

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#187]
**Describe the bug**
The robot player appears to have a material issue

**Steps to reproduce**
1. Open BaseSample
2. Press CTRL+G to play the game

**Expected behavior**
Burt loads with the proper material

**Actual behavior**
Burt is missing materials and appears all white

**Found in Branch**
development August 23

**Comment by lmbr-pip** [comment]
Seems a material issue problem (@AMZN-Olex may have reported this in o3de/o3de)

Other users not reporting this issue on latest so maybe already fixed.

**Comment by AMZN-Olex** [comment]
This issue definitely reproes in o3de-multiplayersample, it could be outdated materials?

![image](https://user-images.githubusercontent.com/5432499/188057831-d9cbdafe-30ca-4d86-be10-55669f9c562e.png)

**Comment by lmbr-pip** [comment]
Materials just need to be fixed and resaved. Have a fix in private branch, will see if it can be cherry-picked out.
