### ISSUE TITLE
Editor Crash related to FBX update

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de-multiplayersample#223]
**Describe the bug**
The editor crashed after I externally updated a FBX (re-export), while I had the prefab that used it open. I also had deleted the .assetinfo (and was going to re-gen it.)

**Steps to reproduce**
1. Open a prefab
2. Alter the FBX that it relies on and save

**Expected behavior**
Everything should update without crashing

**Actual behavior**
Editor crashed

**Found in Branch**
o3de-multiplayersample

**Comment by lmbr-pip** [comment]
@mcphedar Can we get a link to assets and crash logs? Is this generic to any FBX file?

This sounds like this is a generic o3de/o3de issue and should move there.
