### ISSUE TITLE
MPS Expansion: Implement the Jump Pad

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de-multiplayersample#227]
**Is your feature request related to a problem? Please describe.**
The jump pad was intended as an additional player mobility option. The design is simple - When a player steps onto the jump pad they are launched into the air in the direction they are facing. The distance, both horizontally and vertically should be tunable. The jump pad was not implemented for the initial MPS release. Only the model, VFX and SFX were created. 

![image](https://user-images.githubusercontent.com/67011188/220982050-1ea14cd2-f45e-4ffd-a464-3a7c693f461c.png)
 
**Asset Locations**
Model: https://github.com/o3de/o3de-multiplayersample-assets/tree/main/Gems/level_art_mps/Assets/JumpPad
VFX:  Pending final locations for assets and docs
Audio: Pending final locations for assets and docs

**Comment by lmbr-pip** [comment]
This has been delivered in https://github.com/o3de/o3de-multiplayersample/commit/553d3e0ccc7c15f831d1468c78c18854343848c8
