### ISSUE TITLE
MultiplayerSample project cannot be built without workaround due to missing engines_path object

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de-multiplayersample#230]
**Describe the bug**
The MultiplayerSample project fails to configure build files with cmake due to missing engines_path object, and informs the user that the engine needs to be registered before configuring the project - despite the engine already having been registered.
This issue occurs both on Windows and Linux.
As for the workaround, replace o3de-multiplayersample/cmake/EngineFinder.cmake file with a file from the engine source code from o3de/Templates/DefaultProject/Template/cmake/EngineFinder.cmake.

**Steps to reproduce**
1. Build O3DE from github.
2. Make sure the engine is registered by running `scripts/o3de.bash register --this-engine` from the engine directory (replace o3de.bash with o3de.sh on Linux).
3. Follow instructions in the [readme](https://github.com/o3de/o3de-multiplayersample/blob/development/README.md) until the first cmake command (on Linux, use the [Linux readme](https://github.com/o3de/o3de-multiplayersample/blob/development/README_LINUX.md) instead).
4. Attempt to configure build files with the first cmake command in the appropriate readme file.

**Expected behavior**
Build files are generated successfully.

**Actual behavior**
Configuring build files fails due to an error related to engines_path object. See attached logs for details.

**Attachments**
[console.log](https://github.com/o3de/o3de-multiplayersample/files/10824884/console.log)
[CMakeOutput.log](https://github.com/o3de/o3de-multiplayersample/files/10824886/CMakeOutput.log)

**Found in Branch**
MultiplayerSample: Development https://github.com/o3de/o3de-multiplayersample/commit/db4a2403af00bdd034de61a96af8b8ff8711fb9e
O3DE: Development https://github.com/o3de/o3de/commit/37b6a48ccae8efa3da8a7c2295cd34b38d1d5b1f

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by LB-JaroslawGaweda** [comment]
We have encountered this issue on Development (7607430) installer build while using https://github.com/AMZN-Phil/RemoteO3DEProject.git for remote project and https://github.com/AMZN-Phil/RemoteO3DETemplate.git for remote template.
It should be noted that the workaround mentioned above is functional.

**Comment by lmbr-pip** [comment]
Looks like dev needs some updates to match recent engine changes. We expected to be fixed when MPS dev branch is updated prior to release.

**Comment by lmbr-pip** [comment]
I believe this has been addressed by recent merge to dev and https://github.com/o3de/o3de-multiplayersample/pull/242

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed in the latest development branches (MPS: [8340acb](https://github.com/o3de/o3de-multiplayersample/commit/8340acb9a3b141ea4da86f228683cb9c5642a5d6), O3DE: [8fbad22](https://github.com/o3de/o3de/commit/8fbad22e9545137ea45b9019941fe3fea63c0af6)).
