### ISSUE TITLE
Popcorn FX and related assets aren't where they should be

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de-multiplayersample#274]
Popcorn FX `pkfx` assets and the related props, materials, etc, have all been merged into the o3de-mulitplayer project causing issues. These assets should be moved to appropriate Gems so that they can be easily accessed outside of multiplayerample, and the Project included in the mulitplayersample-assets Gem (`Project` directory) needs to be repaired.

Popcorn FX and the related assets (material, shaders, meshes, textures), I assume, were intended to be placed in the following Gems:
* [o3de-multiplayersample-assets](https://github.com/o3de/o3de-multiplayersample-assets)/[Gems](https://github.com/o3de/o3de-multiplayersample-assets/tree/main/Gems)/particlefx_mps/
* [o3de-multiplayersample-assets](https://github.com/o3de/o3de-multiplayersample-assets)/[Gems](https://github.com/o3de/o3de-multiplayersample-assets/tree/main/Gems)/props_mps/
 
The files were added to the o3de-multiplayersample Gem, then removed from the o3de-mulitplayersample-assets Gem here: https://github.com/o3de/o3de-multiplayersample-assets/commit/e2f8067c5ae69015b52e6fad1e463a0b66dc00f1

This has broken the test project **MPS-Asset-Test** that is included in the o3de-mulitplayersample-assets Gem in the Project directory. The Levels/PopcornFXScene doesn't work because it can't access the assets. The particlefx_mps and props_mps Gems are empty and unused.

**Comment by lmbr-pip** [comment]
@micronAMZN can you provide more description of what "causing issues" means?

**Comment by micronAMZN** [comment]
Closing because the more I dig into this to try to explain the issues, the more problems surface. Going to try to find another way to address this.
