### ISSUE TITLE
Energy balls are not rendered server-side

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de-multiplayersample#322]
**Describe the bug**
Energy ball projectiles are not visible on the ServerLauncher, while being visible on the GameLauncher. It should be noted that gems, players and level meshes are visible both on the ServerLauncher and the GameLauncher.

**Steps to reproduce**
1. Follow steps listed here: https://github.com/o3de/o3de-multiplayersample/blob/stabilization/2305/README_LINUX.md to setup MultiplayerSample.
2. Launch ServerLauncher and GameLauncher as described here: https://github.com/o3de/o3de-multiplayersample/blob/development/README_LINUX.md#step-4-setup-client-and-server.
3. Move camera in the ServerLauncher around where the energy balls are moving on the client side.

**Expected behavior**
Energy balls are visible.

**Actual behavior**
Energy balls are invisible.

**Video**

https://user-images.githubusercontent.com/86952082/230317941-4836ce29-6293-47de-9a96-406014d63989.mp4

**Found in Branch**
o3de-multiplayersample: Stabilization/2305 (4cee1b11a04ecbedacadb7dd977f11c8adce0d12)
o3de-multiplayersample-assets: Stabilization/2305 (6739f1027152e68f67be361d77df2296dbf4e800)
o3de: Stabilization/2305 Installer (4/6/2023)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lmbr-pip** [comment]
I believe this by design as a server optimization, many visual cosmetics are not rendered on the server.

**Comment by lmbr-pip** [comment]
ServerLauncher has no audio or particles. The energy balls are particles and so will not render. This is by design and will be covered in the known issue notes for the release (my apologies that these are not in the repository yet - will be coming in the next few days.

**Comment by LB-ArturZieba** [comment]
Confirming the issue has been closed as by design.
