### ISSUE TITLE
No HUD When Using -bg_ConnectToAssetProcessor=0

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-multiplayersample#396]
The HUD doesn't appear when playing the gamelauncher

**Steps to reproduce**
1. Start a server running NewStarbase
2. Run `MultiplayerSample.GameLauncher -bg_ConnectToAssetProcessor=0 --connect` to connect to server

**Expected behavior**
Game is running with the HUD visible

**Actual behavior**
No HUD is visible. User cannot exit the game because even the pause menu doesnt appear
![image](https://user-images.githubusercontent.com/32776221/236313843-047dc245-02dc-421b-994c-8cd0de5c17db.png)

**Found in Branch**
development

**Comment by AMZN-Gene** [comment]
critical, cant make a packaged game without a hud

**Comment by AMZN-daimini** [comment]
I tried reproducing this with GameLift Anywhere, but I always get the UI correctly. (I do have the -bg_ConnectToAssetProcessor=0).
I tested both with the regular method in the doc and by building the client via VS (to have access to the debugger), but the UI always shows.
