### ISSUE TITLE
No license specified for assets in this repo (BURT etc.)

### ISSUE THREAD

**Issue by poVoq** [o3de/o3de-multiplayersample#398]
Contrary to the assets in the separate asset repo, the ones included in this repo are not clearly licensed, for example this model here: https://github.com/o3de/o3de-multiplayersample/tree/development/BURT

Should we assume the model and animations are also Apache2 licensed?

Thanks!

**Comment by AMZN-Gene** [comment]
@mcphedar any legal information you can provide for using BURT (Y-Bot?)

**Comment by lmbr-pip** [comment]
Burt is being removed: https://github.com/o3de/o3de-multiplayersample/pull/409

**Comment by mcphedar** [comment]
The BURT directory has been removed. Those assets are no longer needed for the MPS.
