### ISSUE TITLE
Requested level not found: 'startmenu'

### ISSUE THREAD

**Issue by mafster** [o3de/o3de-multiplayersample#426]
**Describe the bug**
Default clean install of O3DE + multiplersample test on windows 11 didnt work. Due to missing level "startmenu"

**Steps to reproduce**
1. Install OD3E with installer (windows)
2. Install multiplayersample along with assets repo. Follow instructions exactly (including both on `main` branch). All went ahead without errors
3. Built project
4. Run launch_server.cmd (appears to work (no errors))
5. Run launch_client.cmd

**Expected behavior**
Game should launch locally for testing.

**Actual behavior**
Get error popup saying startmenu level not found (see pic)

**Assets required**
Default o3de-multplersample and corresponding assets repo

**Screenshots/Video**
![image](https://github.com/o3de/o3de-multiplayersample/assets/6612068/c9b5710a-4cb9-4bcd-a8ca-3c0a1f9aaf1a)

**Found in Branch**
main

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11 Home
 - Version 22H2
 - CPU AMD Ryzen 9 5900HX with Radeon Graphics
 - GPU ^^ Radeon Graphics
 - Memory 64GB

**Additional context**
Really keen on this engine but would expect default, no custom changes, behaviour main branch should work straight off the bat. The user experience would definitely invite more people on board if smooth.

**Comment by mafster** [comment]
I think this can be resolved by first opening the project and select the level startmenu and then closing again (or running from inside the editor). This is not explicitly stated in the instructions. Just running the commands either via the commandline or respective cmd files (if on windows) does not launch it.

**Comment by AMZN-Gene** [comment]
Nice find! Thanks for providing a work around as well. I think if you pressed "OK" the process also continues, is that right?

**Comment by mafster** [comment]
On the intialization failed screen? No pressing "OK" doesnt work. It "loads" but its just a greay kinda QT screen. No connection or anything. I even waited a good 5 mins to just make sure it wasnt some crazy loading. Only worked once i

**Comment by mafster** [comment]
"Ok" nn the intialization failed screen i posted? No pressing "OK" didn't work. It "loads" but its just a grey kinda QT type window. No connection or anything. I even waited a good 5 mins to just make sure it wasnt some crazy loading. Only worked once into the editor and selected startmenu. (i havent tried selecting any other level so unsure if its specifically that menu.)
