### ISSUE TITLE
MultiplayerSample GameLauncher fails to recognize inputs during the game

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de-multiplayersample#467]
**Describe the bug**
Clients launched via built MultiplayerSample.GameLauncher fail to recognize keyboard, mouse, and gamepad inputs during the game match.

The issue was observed for all MultiplayerSample project levels with controllable inputs such as _NewStarbase_ and _Gameplaytest_ levels. The only time GameLauncher client was able to recognize input was in _StartMenu_ level.

Please note that inputs in Editor client and MultiplayerSample.ServerLauncher were recognized correctly and that this issue occurs only on Windows. 

For further information please refer to the attached video file and logs.

**Steps to reproduce**

1. Build a Source O3DE Engine.
2. Build MultiplayerSample project following https://github.com/o3de/o3de-multiplayersample/blob/development/README.md instruction (specific steps were Step 1/Option 1 -> Step 2 -> Step 3/Option 2).
3. Process assets for the MultiplayerSample project.
4. Launch the game server with _MultiplayerSample.ServerLauncher.exe --console-command-file=launch_server.cfg_ command.
5. Launch the client with _MultiplayerSample.GameLauncher.exe --console-command-file=launch_client.cfg_ command.
6. Try to move the player controller of the launched client with keyboard and mouse. 

**Expected behavior**
Player controller of the launched MultiplayerSample.GameLauncher client can be controlled with keyboard and mouse inputs.

**Actual behavior**
Player controller of the launched MultiplayerSample.GameLauncher client does not react to keyboard and mouse inputs during the match.

**Screenshots/Video**

https://github.com/o3de/o3de-multiplayersample/assets/86953456/4ebb06db-4962-42a0-a7f3-227c8154543c

**Found in Branch**
Stabilization/2310

**Commit ID from** [o3de/o3de-multiplayersample](https://github.com/o3de/o3de-multiplayersample) **Repository**
[a0654e0](https://github.com/o3de/o3de-multiplayersample/commit/a0654e071c942a86887627b1b1fa4739cd442145)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Server.log](https://github.com/o3de/o3de-multiplayersample/files/12522368/Server.log)
[Game.log](https://github.com/o3de/o3de-multiplayersample/files/12522369/Game.log)

**Comment by LB-ArturZieba** [comment]
I also observed this issue on Ubuntu 22.04.3 with following branches used in the setup:
* o3de: Stabilization/2310 (7aabf7f)
* o3de-multiplayersample: Stabilization/2310 (149bf33)
* o3de-multiplayersample-assets: Stabilization/2310 (cd6d15f)

**Comment by AMZN-Gene** [comment]
I cannot repo this issue. Closing for now... feel free to reopen if mouse/keyboard input still doesn't work.
