### ISSUE TITLE
Failed to Build 

### ISSUE THREAD

**Issue by IndieDev99** [o3de/o3de-multiplayersample#473]
return AZStd::make_pair<Multiplayer::PrefabEntityId, AZ::Transform>(

                        ^

 O3DE/Projects/NewProject/Gem/Code/Source/Spawners/RoundRobinSpawner.cpp(45,13): note: You cannot bind an lvalue to an rvalue reference

              prefabEntityId, spawner->GetEntity()->GetTransform()->GetWorldTM());

              ^

  C:\O3DE\23.10.0\Code\Framework\AzCore\AzCore/std/utils.h(291,20): note: see declaration of 'AZStd::make_pair'

      constexpr auto make_pair(T1&& value1, T2&& value2)

**Comment by AMZN-Gene** [comment]
@IndieDev99, is this using the Multiplayer Template project? (I see the path is "NewProject" and not Multiplayer Sample).
The RoundRobinSpawner isn't really needed anymore now that the Multiplayer gem (built into the engine), contains a Simple Network Player Spawner.
You could actually just delete this code (and remove the .cpp/.h from the Gem/Code/newproject_files.cmake) and just the Simple Spawner.

**Comment by AMZN-Gene** [comment]
The new Multiplayer Template fixes this issue.
Accessible [here](https://github.com/o3de/o3de-extras/tree/development/Templates/Multiplayer). Let me know if it does the trick, or reopen this issue :)
