### ISSUE TITLE
o3de-multiplayersample project fails to configure

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de-multiplayersample#75]
**Describe the bug**
Trying to configure and build the _o3de-multiplayersample_ project cloned from https://github.com/aws-lumberyard-dev/o3de-multiplayersample will fail during the configuration process.

This occurs regardless of the configuration method used. Configuring with either Powershell or Project Manager results in the same errors.

For further information please refer to the attached _CMakeProjectBuildError.log_ file.

**Steps to reproduce**

1. Obtain the latest o3de build.
2. Clone _o3de-multiplayersample_ project from _https://github.com/aws-lumberyard-dev/o3de-multiplayersample_ into the o3de directory.
3. Run the `cmake -B build/windows_vs2019 -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages -DLY_UNITY_BUILD=ON -DLY_PROJECTS=o3de-multiplayersample` command.

**Expected behavior**
The project configures successfully.

**Actual behavior**
The project fails to configure.

**Found in Branch**
Stabilization_2110 (9dac727)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**

[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/7441823/CMakeProjectBuildError.log)

**Comment by lmbr-pip** [comment]
Please reopen issue if you have these problems on the main repro.

**Comment by LB-MateuszSzweda** [comment]
Indeed cloning and using  https://github.com/o3de/o3de-multiplayersample instead of https://github.com/aws-lumberyard-dev/o3de-multiplayersample resolved the problem.

After cloning from o3de multiplayersample project configured and built successfully on both Stabilization_2110 and Development branches. Thank you.
