### ISSUE TITLE
[ServerLauncher] Server launcher couldn't start due to the missing CrySystem.dll

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de-multiplayersample#79]
### Repro Steps
1. Build and run the Asset Processor to process all the assets for MultiplayerSample
2. Clear the build folder build\windows_vs2019\bin\profile
3. Build the MultiplayerSample.ServerLauncher target
4. Launch the server launcher from CLI: MultiplayerSample.ServerLauncher.exe --console-command-file=server.cfg -bg_ConnectToAssetProcessor=0

### Expected Result
Server can be launched without issues

### Actual Result
Got the following popup error and no log file is generated:
![image](https://user-images.githubusercontent.com/68558268/140393997-b990a4d4-50b6-42e4-9eb8-be48b37c41c2.png)

The current workaround is to build CrySystem.dll manually for the server launcher.

**Comment by lmbr-pip** [comment]
Appears to have missing dependency declaration. Needs fix for MPS

**Comment by lmbr-pip** [comment]
@lmbr-pip - confirm on clean build with just server launcher.

**Comment by lmbr-pip** [comment]
Built latest dev, ran the following commands on a clean build folder on o3de-multiplayer sample

```
<delete windows\vs_2019 folder>
cmake -B build/windows_vs2019 -S . -G "Visual Studio 16" -DLY_3RDPARTY_PATH=E:\o3de-packages
cmake --build E:\dev\o3de\o3de-multiplayersample\build\windows_vs2019 --target MultiplayerSample.ServerLauncher --config profile -- /m /nologo
```

* CrySystem.dll is built
* Server launcher could be executed before complaining about lack of AssetProcessor connection

Closing out as did not reproduce. Please reopen if issue persists.
