### ISSUE TITLE
Add default cvar to enable ctrl-g experience with multiplayer support in the Editor

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de-multiplayersample#90]
- Config .cfg files are now loaded at the project level
- We can set the required cvar via a .cfg file that are loaded by the Editor when MultiplayerSample is on (perhaps in system component if necessary)
- Or enable them when Multiplayer gem is active for a project?

**Comment by AMZN-Gene** [comment]
editorsv_enabled is false by default. we'd want that to be true for MultiplayerSample project.

**Comment by lmbr-pip** [comment]
For MPS make editorsv_enabled= true by default.

**Comment by AMZN-Gene** [comment]
It would be nice if this was enabled by default when using the MP gem, but that get is enabled for the default project so it might be confusing. 
This should definitely be enabled for MultiplayerSample though...
MultiplayerSample/editor.cfg sets _editorsv_enabled=true_. Closing as fixed.
