### ISSUE TITLE
MultiplayerSample became unresponsive on Android

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de-multiplayersample#94]
MultiplayerSample could be built successfully for Android but after deployed the application to an Android device, it couldn't load the base level and became unresponsive. Log file is attached. Got a pop up message on the phone saying that MultiplayerSample wasn't responding.

[andoird_log.txt](https://github.com/o3de/o3de-multiplayersample/files/7584740/andoird_log.txt)

**Comment by lmbr-pip** [comment]
Created related bug as logs should not say 'Amazon Lumberyard'

Do not see level load happening in logs (as stated by reporter). Need to repro / get assistance to see how progress should be made as logs do not point to anything obvious.

**Comment by lmbr-pip** [comment]
Needs help repro issues and find actual cause.

**Comment by lmbr-pip** [comment]
@junbo75 Can you provide device specs in ticket?

@lmbr-pip Reach out to sig-testing for help.

**Comment by junbo75** [comment]
@lmbr-pip I cannot repro this issue on Android now.
